branches:
  except:
    - road_racing_rewrite
    - 2016_reorg_diff
    - 2017_diff

git:
  depth: 3

notifications:
  email:
    on_success: never
    on_failure: change

language: python

python:
  - '3.6'

sudo: required

cache: apt

addons:
  apt:
    packages:
      - ncftp
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - lmodern
      - po4a
      # - texlive-extra-utils # texfot

install:
  - git checkout $TRAVIS_BRANCH # check out current branch - Else we are in detached HEAD
  - scripts/travis/install.sh
  - export PATH=$PATH:$HOME/local/latexdiff/bin:$HOME/local/latexmk/bin

script:
  - scripts/build/rulebook.sh -t
  - scripts/build/diff-all.sh -t
  - scripts/build/translation.sh -t

after_script:
  - scripts/travis/after.sh
